# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

import java as _java
from pytale.components import Component

_TreasureChestBlock = _java.type(
    "com.hypixel.hytale.builtin.adventure.objectives.blockstates.TreasureChestBlock"
)


class TreasureChestBlock(Component):
    _java_class = _TreasureChestBlock

    @property
    def is_opened(self) -> bool:
        return self._java.isOpened()

    @is_opened.setter
    def is_opened(self, value: bool) -> None:
        self._java.setOpened(value)
