# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_ObjectiveHistoryComponent = _java.type(
    "com.hypixel.hytale.builtin.adventure.objectives.components.ObjectiveHistoryComponent"
)


class ObjectiveHistoryComponent(Component):
    _java_class = _ObjectiveHistoryComponent

    @property
    def objective_history_map(self) -> "JavaObject":
        return self._java.getObjectiveHistoryMap()

    @property
    def objective_line_history_map(self) -> "JavaObject":
        return self._java.getObjectiveLineHistoryMap()
