# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_CreativeHubEntityConfig = _java.type(
    "com.hypixel.hytale.builtin.creativehub.config.CreativeHubEntityConfig"
)


class CreativeHubEntityConfig(Component):
    _java_class = _CreativeHubEntityConfig

    @property
    def parent_hub_world_uuid(self) -> "JavaObject | None":
        return self._java.getParentHubWorldUuid()

    @parent_hub_world_uuid.setter
    def parent_hub_world_uuid(self, value: "JavaObject") -> None:
        self._java.setParentHubWorldUuid(value)
