# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_ObjectiveLocationMarker = _java.type(
    "com.hypixel.hytale.builtin.adventure.objectives.markers.objectivelocation.ObjectiveLocationMarker"
)


class ObjectiveLocationMarker(Component):
    _java_class = _ObjectiveLocationMarker

    @property
    def active_objective(self) -> "JavaObject | None":
        return self._java.getActiveObjective()

    @active_objective.setter
    def active_objective(self, value: "JavaObject") -> None:
        self._java.setActiveObjective(value)

    @property
    def area(self) -> "JavaObject":
        return self._java.getArea()

    @property
    def objective_location_marker_id(self) -> str:
        return self._java.getObjectiveLocationMarkerId()

    @objective_location_marker_id.setter
    def objective_location_marker_id(self, value: str) -> None:
        self._java.setObjectiveLocationMarkerId(value)

    @property
    def untrack_packet(self) -> "JavaObject":
        return self._java.getUntrackPacket()

    @untrack_packet.setter
    def untrack_packet(self, value: "JavaObject") -> None:
        self._java.setUntrackPacket(value)
