# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_ReachLocationMarker = _java.type(
    "com.hypixel.hytale.builtin.adventure.objectives.markers.reachlocation.ReachLocationMarker"
)


class ReachLocationMarker(Component):
    _java_class = _ReachLocationMarker

    @property
    def location_name(self) -> str | None:
        return self._java.getLocationName()

    @property
    def marker_id(self) -> str:
        return self._java.getMarkerId()

    @property
    def players(self) -> "JavaObject":
        return self._java.getPlayers()
