# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_ActiveSlotInventoryComponent = _java.type(
    "com.hypixel.hytale.server.core.inventory.ActiveSlotInventoryComponent"
)

_InventoryComponent = _java.type(
    "com.hypixel.hytale.server.core.inventory.InventoryComponent"
)

_InventoryComponent_Armor = _java.type(
    "com.hypixel.hytale.server.core.inventory.InventoryComponent$Armor"
)

_InventoryComponent_Backpack = _java.type(
    "com.hypixel.hytale.server.core.inventory.InventoryComponent$Backpack"
)

_InventoryComponent_Combined = _java.type(
    "com.hypixel.hytale.server.core.inventory.InventoryComponent$Combined"
)

_InventoryComponent_Hotbar = _java.type(
    "com.hypixel.hytale.server.core.inventory.InventoryComponent$Hotbar"
)

_InventoryComponent_Storage = _java.type(
    "com.hypixel.hytale.server.core.inventory.InventoryComponent$Storage"
)

_InventoryComponent_Tool = _java.type(
    "com.hypixel.hytale.server.core.inventory.InventoryComponent$Tool"
)

_InventoryComponent_Utility = _java.type(
    "com.hypixel.hytale.server.core.inventory.InventoryComponent$Utility"
)


class ActiveSlotInventoryComponent(InventoryComponent):
    _java_class = _ActiveSlotInventoryComponent

    @property
    def active_item(self) -> "JavaObject | None":
        return self._java.getActiveItem()

    @property
    def active_slot(self) -> int:
        return self._java.getActiveSlot()

    @property
    def section_id(self) -> int:
        return self._java.getSectionId()


class InventoryComponent(Component):
    _java_class = _InventoryComponent

    @property
    def change_events(self) -> "JavaObject":
        return self._java.getChangeEvents()

    @property
    def inventory(self) -> "JavaObject":
        return self._java.getInventory()

    class Armor(InventoryComponent):
        _java_class = _InventoryComponent_Armor

    class Backpack(InventoryComponent):
        _java_class = _InventoryComponent_Backpack

    class Combined(Component):
        _java_class = _InventoryComponent_Combined

        @property
        def inventories(self) -> "JavaObject":
            return self._java.getInventories()

    class Hotbar(ActiveSlotInventoryComponent):
        _java_class = _InventoryComponent_Hotbar

        @property
        def section_id(self) -> int:
            return self._java.getSectionId()

    class Storage(InventoryComponent):
        _java_class = _InventoryComponent_Storage

    class Tool(ActiveSlotInventoryComponent):
        _java_class = _InventoryComponent_Tool

        @property
        def is_using_tools_item(self) -> bool:
            return self._java.isUsingToolsItem()

        @is_using_tools_item.setter
        def is_using_tools_item(self, value: bool) -> None:
            self._java.setUsingToolsItem(value)

        @property
        def section_id(self) -> int:
            return self._java.getSectionId()

    class Utility(ActiveSlotInventoryComponent):
        _java_class = _InventoryComponent_Utility

        @property
        def section_id(self) -> int:
            return self._java.getSectionId()
