# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

import java as _java
from pytale.components import Component

_PluginListPageManager_SessionSettings = _java.type(
    "com.hypixel.hytale.server.core.plugin.PluginListPageManager$SessionSettings"
)


class PluginListPageManager_SessionSettings(Component):
    _java_class = _PluginListPageManager_SessionSettings
