# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_InstanceEntityConfig = _java.type(
    "com.hypixel.hytale.builtin.instances.config.InstanceEntityConfig"
)


class InstanceEntityConfig(Component):
    _java_class = _InstanceEntityConfig

    @property
    def return_point(self) -> "JavaObject":
        return self._java.getReturnPoint()

    @return_point.setter
    def return_point(self, value: "JavaObject") -> None:
        self._java.setReturnPoint(value)

    @property
    def return_point_override(self) -> "JavaObject":
        return self._java.getReturnPointOverride()

    @return_point_override.setter
    def return_point_override(self, value: "JavaObject") -> None:
        self._java.setReturnPointOverride(value)
