# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_BlockMapMarker = _java.type(
    "com.hypixel.hytale.server.core.universe.world.meta.state.BlockMapMarker"
)

_LaunchPad = _java.type(
    "com.hypixel.hytale.server.core.universe.world.meta.state.LaunchPad"
)

_RespawnBlock = _java.type(
    "com.hypixel.hytale.server.core.universe.world.meta.state.RespawnBlock"
)


class BlockMapMarker(Component):
    _java_class = _BlockMapMarker

    @property
    def icon(self) -> str:
        return self._java.getIcon()

    @property
    def name(self) -> str:
        return self._java.getName()


class LaunchPad(Component):
    _java_class = _LaunchPad

    @property
    def is_players_only(self) -> bool:
        return self._java.isPlayersOnly()

    @property
    def velocity_x(self) -> float:
        return self._java.getVelocityX()

    @property
    def velocity_y(self) -> float:
        return self._java.getVelocityY()

    @property
    def velocity_z(self) -> float:
        return self._java.getVelocityZ()


class RespawnBlock(Component):
    _java_class = _RespawnBlock

    @property
    def owner_uuid(self) -> "JavaObject":
        return self._java.getOwnerUUID()

    @owner_uuid.setter
    def owner_uuid(self, value: "JavaObject") -> None:
        self._java.setOwnerUUID(value)
