# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_PlayerMemories = _java.type(
    "com.hypixel.hytale.builtin.adventure.memories.component.PlayerMemories"
)


class PlayerMemories(Component):
    _java_class = _PlayerMemories

    @property
    def memories_capacity(self) -> int:
        return self._java.getMemoriesCapacity()

    @memories_capacity.setter
    def memories_capacity(self, value: int) -> None:
        self._java.setMemoriesCapacity(value)

    @property
    def recorded_memories(self) -> "JavaObject":
        return self._java.getRecordedMemories()
