# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_ChunkSpawnData = _java.type(
    "com.hypixel.hytale.server.spawning.world.component.ChunkSpawnData"
)

_ChunkSpawnedNPCData = _java.type(
    "com.hypixel.hytale.server.spawning.world.component.ChunkSpawnedNPCData"
)

_SpawnJobData = _java.type(
    "com.hypixel.hytale.server.spawning.world.component.SpawnJobData"
)


class ChunkSpawnData(Component):
    _java_class = _ChunkSpawnData

    @property
    def chunk_environment_spawn_data_map(self) -> "JavaObject":
        return self._java.getChunkEnvironmentSpawnDataMap()

    @property
    def is_on_spawn_cooldown(self) -> bool:
        return self._java.isOnSpawnCooldown()

    @property
    def is_started(self) -> bool:
        return self._java.isStarted()

    @is_started.setter
    def is_started(self, value: bool) -> None:
        self._java.setStarted(value)

    @property
    def last_spawn(self) -> int:
        return self._java.getLastSpawn()

    @last_spawn.setter
    def last_spawn(self, value: int) -> None:
        self._java.setLastSpawn(value)


class ChunkSpawnedNPCData(Component):
    _java_class = _ChunkSpawnedNPCData


class SpawnJobData(Component):
    _java_class = _SpawnJobData

    @property
    def budget_used(self) -> int:
        return self._java.getBudgetUsed()

    @budget_used.setter
    def budget_used(self, value: int) -> None:
        self._java.setBudgetUsed(value)

    @property
    def environment(self) -> "JavaObject":
        return self._java.getEnvironment()

    @property
    def environment_index(self) -> int:
        return self._java.getEnvironmentIndex()

    @property
    def flock_asset(self) -> "JavaObject":
        return self._java.getFlockAsset()

    @property
    def flock_size(self) -> int:
        return self._java.getFlockSize()

    @property
    def is_ignore_fully_populated(self) -> bool:
        return self._java.isIgnoreFullyPopulated()

    @is_ignore_fully_populated.setter
    def is_ignore_fully_populated(self, value: bool) -> None:
        self._java.setIgnoreFullyPopulated(value)

    @property
    def is_spawn_frozen(self) -> bool:
        return self._java.isSpawnFrozen()

    @is_spawn_frozen.setter
    def is_spawn_frozen(self, value: bool) -> None:
        self._java.setSpawnFrozen(value)

    @property
    def is_terminated(self) -> bool:
        return self._java.isTerminated()

    @property
    def job_id(self) -> int:
        return self._java.getJobId()

    @property
    def rejection_map(self) -> "JavaObject":
        return self._java.getRejectionMap()

    @property
    def role_index(self) -> int:
        return self._java.getRoleIndex()

    @property
    def spans_success(self) -> int:
        return self._java.getSpansSuccess()

    @property
    def spans_tried(self) -> int:
        return self._java.getSpansTried()

    @property
    def spawn_config(self) -> "JavaObject":
        return self._java.getSpawnConfig()

    @property
    def spawn_config_index(self) -> int:
        return self._java.getSpawnConfigIndex()

    @property
    def spawning_context(self) -> "JavaObject":
        return self._java.getSpawningContext()

    @property
    def suppression_span_helper(self) -> "JavaObject":
        return self._java.getSuppressionSpanHelper()

    @property
    def total_budget_used(self) -> int:
        return self._java.getTotalBudgetUsed()

    @property
    def total_columns_blocked(self) -> int:
        return self._java.getTotalColumnsBlocked()

    @property
    def total_columns_tested(self) -> int:
        return self._java.getTotalColumnsTested()
