# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_DamageDataComponent = _java.type(
    "com.hypixel.hytale.server.core.entity.damage.DamageDataComponent"
)


class DamageDataComponent(Component):
    _java_class = _DamageDataComponent

    @property
    def current_wielding(self) -> "JavaObject | None":
        return self._java.getCurrentWielding()

    @current_wielding.setter
    def current_wielding(self, value: "JavaObject") -> None:
        self._java.setCurrentWielding(value)

    @property
    def last_charge_time(self) -> "JavaObject | None":
        return self._java.getLastChargeTime()

    @last_charge_time.setter
    def last_charge_time(self, value: "JavaObject") -> None:
        self._java.setLastChargeTime(value)

    @property
    def last_combat_action(self) -> "JavaObject":
        return self._java.getLastCombatAction()

    @last_combat_action.setter
    def last_combat_action(self, value: "JavaObject") -> None:
        self._java.setLastCombatAction(value)

    @property
    def last_damage_time(self) -> "JavaObject":
        return self._java.getLastDamageTime()

    @last_damage_time.setter
    def last_damage_time(self, value: "JavaObject") -> None:
        self._java.setLastDamageTime(value)
