# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_EffectControllerComponent = _java.type(
    "com.hypixel.hytale.server.core.entity.effect.EffectControllerComponent"
)


class EffectControllerComponent(Component):
    _java_class = _EffectControllerComponent

    @property
    def active_effect_indexes(self) -> "JavaObject":
        return self._java.getActiveEffectIndexes()

    @property
    def active_effects(self) -> "JavaObject":
        return self._java.getActiveEffects()

    @property
    def all_active_entity_effects(self) -> "JavaObject | None":
        return self._java.getAllActiveEntityEffects()

    @property
    def is_invulnerable(self) -> bool:
        return self._java.isInvulnerable()

    @is_invulnerable.setter
    def is_invulnerable(self, value: bool) -> None:
        self._java.setInvulnerable(value)
