# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_EntityGroup = _java.type("com.hypixel.hytale.server.core.entity.group.EntityGroup")


class EntityGroup(Component):
    _java_class = _EntityGroup

    @property
    def first(self) -> "JavaObject | None":
        return self._java.getFirst()

    @property
    def is_dissolved(self) -> bool:
        return self._java.isDissolved()

    @is_dissolved.setter
    def is_dissolved(self, value: bool) -> None:
        self._java.setDissolved(value)

    @property
    def leader_ref(self) -> "JavaObject | None":
        return self._java.getLeaderRef()

    @leader_ref.setter
    def leader_ref(self, value: "JavaObject") -> None:
        self._java.setLeaderRef(value)

    @property
    def member_list(self) -> "JavaObject":
        return self._java.getMemberList()
