# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component
from pytale.math import Vector3

if TYPE_CHECKING:
    from java import JavaObject

_KnockbackComponent = _java.type(
    "com.hypixel.hytale.server.core.entity.knockback.KnockbackComponent"
)


class KnockbackComponent(Component):
    _java_class = _KnockbackComponent

    @property
    def duration(self) -> float:
        return self._java.getDuration()

    @duration.setter
    def duration(self, value: float) -> None:
        self._java.setDuration(value)

    @property
    def timer(self) -> float:
        return self._java.getTimer()

    @timer.setter
    def timer(self, value: float) -> None:
        self._java.setTimer(value)

    @property
    def velocity(self) -> Vector3:
        return Vector3(self._java.getVelocity())

    @velocity.setter
    def velocity(self, value: Vector3) -> None:
        self._java.setVelocity(value._java)

    @property
    def velocity_config(self) -> "JavaObject | None":
        return self._java.getVelocityConfig()

    @velocity_config.setter
    def velocity_config(self, value: "JavaObject") -> None:
        self._java.setVelocityConfig(value)

    @property
    def velocity_type(self) -> "JavaObject":
        return self._java.getVelocityType()

    @velocity_type.setter
    def velocity_type(self, value: "JavaObject") -> None:
        self._java.setVelocityType(value)
