# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_MovementStatesComponent = _java.type(
    "com.hypixel.hytale.server.core.entity.movement.MovementStatesComponent"
)


class MovementStatesComponent(Component):
    _java_class = _MovementStatesComponent

    @property
    def movement_states(self) -> "JavaObject":
        return self._java.getMovementStates()

    @movement_states.setter
    def movement_states(self, value: "JavaObject") -> None:
        self._java.setMovementStates(value)

    @property
    def sent_movement_states(self) -> "JavaObject":
        return self._java.getSentMovementStates()

    @sent_movement_states.setter
    def sent_movement_states(self, value: "JavaObject") -> None:
        self._java.setSentMovementStates(value)
