# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

import java as _java
from pytale.components import Component

_Nameplate = _java.type("com.hypixel.hytale.server.core.entity.nameplate.Nameplate")


class Nameplate(Component):
    _java_class = _Nameplate

    @property
    def text(self) -> str:
        return self._java.getText()

    @text.setter
    def text(self, value: str) -> None:
        self._java.setText(value)
