# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_PredictedProjectile = _java.type(
    "com.hypixel.hytale.server.core.modules.projectile.component.PredictedProjectile"
)

_Projectile = _java.type(
    "com.hypixel.hytale.server.core.modules.projectile.component.Projectile"
)


class PredictedProjectile(Component):
    _java_class = _PredictedProjectile

    @property
    def uuid(self) -> "JavaObject":
        return self._java.getUuid()


class Projectile(Component):
    _java_class = _Projectile
