# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

import java as _java
from pytale.components import Component

_TeleportPlugin_WarpComponent = _java.type(
    "com.hypixel.hytale.builtin.teleport.TeleportPlugin$WarpComponent"
)


class TeleportPlugin_WarpComponent(Component):
    _java_class = _TeleportPlugin_WarpComponent
