# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

import java as _java
from pytale.components import Component

_TeleportHistory = _java.type(
    "com.hypixel.hytale.builtin.teleport.components.TeleportHistory"
)


class TeleportHistory(Component):
    _java_class = _TeleportHistory

    @property
    def back_size(self) -> int:
        return self._java.getBackSize()

    @property
    def forward_size(self) -> int:
        return self._java.getForwardSize()
