# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_BlockHealthChunk = _java.type(
    "com.hypixel.hytale.server.core.modules.blockhealth.BlockHealthChunk"
)


class BlockHealthChunk(Component):
    _java_class = _BlockHealthChunk

    @property
    def block_fragility_map(self) -> "JavaObject":
        return self._java.getBlockFragilityMap()

    @property
    def block_health_map(self) -> "JavaObject":
        return self._java.getBlockHealthMap()

    @property
    def last_repair_game_time(self) -> "JavaObject":
        return self._java.getLastRepairGameTime()

    @last_repair_game_time.setter
    def last_repair_game_time(self, value: "JavaObject") -> None:
        self._java.setLastRepairGameTime(value)
