# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_EntityStatMap = _java.type(
    "com.hypixel.hytale.server.core.modules.entitystats.EntityStatMap"
)


class EntityStatMap(Component):
    _java_class = _EntityStatMap

    @property
    def self_stat_values(self) -> "JavaObject":
        return self._java.getSelfStatValues()

    @property
    def self_updates(self) -> "JavaObject":
        return self._java.getSelfUpdates()

    @property
    def stat_modifiers_manager(self) -> "JavaObject":
        return self._java.getStatModifiersManager()
