# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_UIComponentList = _java.type(
    "com.hypixel.hytale.server.core.modules.entityui.UIComponentList"
)


class UIComponentList(Component):
    _java_class = _UIComponentList

    @property
    def component_ids(self) -> "JavaObject":
        return self._java.getComponentIds()
