# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_PrefabSpawnerBlock = _java.type(
    "com.hypixel.hytale.server.core.modules.prefabspawner.PrefabSpawnerBlock"
)


class PrefabSpawnerBlock(Component):
    _java_class = _PrefabSpawnerBlock

    @property
    def is_fit_heightmap(self) -> bool:
        return self._java.isFitHeightmap()

    @is_fit_heightmap.setter
    def is_fit_heightmap(self, value: bool) -> None:
        self._java.setFitHeightmap(value)

    @property
    def is_inherit_height_condition(self) -> bool:
        return self._java.isInheritHeightCondition()

    @is_inherit_height_condition.setter
    def is_inherit_height_condition(self, value: bool) -> None:
        self._java.setInheritHeightCondition(value)

    @property
    def is_inherit_seed(self) -> bool:
        return self._java.isInheritSeed()

    @is_inherit_seed.setter
    def is_inherit_seed(self, value: bool) -> None:
        self._java.setInheritSeed(value)

    @property
    def prefab_path(self) -> str:
        return self._java.getPrefabPath()

    @prefab_path.setter
    def prefab_path(self, value: str) -> None:
        self._java.setPrefabPath(value)

    @property
    def prefab_weights(self) -> "JavaObject":
        return self._java.getPrefabWeights()

    @prefab_weights.setter
    def prefab_weights(self, value: "JavaObject") -> None:
        self._java.setPrefabWeights(value)
