"""Base class for auto-generated ECS component wrappers"""

from typing import TYPE_CHECKING, ClassVar

from pytale._java_wrapper import JavaWrapper

if TYPE_CHECKING:
    from java import JavaClass


class Component(JavaWrapper):
    """Base for classes generated by `pytale-tools generate -t components` from
    com.hypixel.hytale.component.Component subclasses in the server jar."""

    _java_class: ClassVar["JavaClass"]
