# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_BenchBlock = _java.type("com.hypixel.hytale.builtin.crafting.component.BenchBlock")

_CraftingManager = _java.type(
    "com.hypixel.hytale.builtin.crafting.component.CraftingManager"
)

_ProcessingBenchBlock = _java.type(
    "com.hypixel.hytale.builtin.crafting.component.ProcessingBenchBlock"
)


class BenchBlock(Component):
    _java_class = _BenchBlock

    @property
    def tier_level(self) -> int:
        return self._java.getTierLevel()

    @tier_level.setter
    def tier_level(self, value: int) -> None:
        self._java.setTierLevel(value)

    @property
    def tier_state_name(self) -> str:
        return self._java.getTierStateName()

    @property
    def upgrade_items(self) -> "JavaObject":
        return self._java.getUpgradeItems()

    @upgrade_items.setter
    def upgrade_items(self, value: "JavaObject") -> None:
        self._java.setUpgradeItems(value)

    @property
    def windows(self) -> "JavaObject":
        return self._java.getWindows()


class CraftingManager(Component):
    _java_class = _CraftingManager

    @property
    def remaining_queue_size(self) -> int:
        return self._java.getRemainingQueueSize()


class ProcessingBenchBlock(Component):
    _java_class = _ProcessingBenchBlock

    @property
    def bench(self) -> "JavaObject | None":
        return self._java.getBench()

    @property
    def fuel_container(self) -> "JavaObject":
        return self._java.getFuelContainer()

    @property
    def fuel_time(self) -> float:
        return self._java.getFuelTime()

    @property
    def input_container(self) -> "JavaObject":
        return self._java.getInputContainer()

    @property
    def input_progress(self) -> float:
        return self._java.getInputProgress()

    @input_progress.setter
    def input_progress(self, value: float) -> None:
        self._java.setInputProgress(value)

    @property
    def is_active(self) -> bool:
        return self._java.isActive()

    @property
    def item_container(self) -> "JavaObject | None":
        return self._java.getItemContainer()

    @property
    def last_tick_game_time(self) -> "JavaObject | None":
        return self._java.getLastTickGameTime()

    @last_tick_game_time.setter
    def last_tick_game_time(self, value: "JavaObject") -> None:
        self._java.setLastTickGameTime(value)

    @property
    def output_container(self) -> "JavaObject":
        return self._java.getOutputContainer()

    @property
    def processing_bench(self) -> "JavaObject | None":
        return self._java.getProcessingBench()

    @property
    def processing_fuel_slots(self) -> "JavaObject":
        return self._java.getProcessingFuelSlots()

    @property
    def processing_slots(self) -> "JavaObject":
        return self._java.getProcessingSlots()

    @property
    def recipe(self) -> "JavaObject | None":
        return self._java.getRecipe()
