# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_TempUnknownComponent = _java.type(
    "com.hypixel.hytale.component.data.unknown.TempUnknownComponent"
)

_UnknownComponents = _java.type(
    "com.hypixel.hytale.component.data.unknown.UnknownComponents"
)


class TempUnknownComponent(Component):
    _java_class = _TempUnknownComponent

    @property
    def document(self) -> "JavaObject":
        return self._java.getDocument()


class UnknownComponents(Component):
    _java_class = _UnknownComponents

    @property
    def unknown_components(self) -> "JavaObject":
        return self._java.getUnknownComponents()
