# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_VoidEvent = _java.type(
    "com.hypixel.hytale.builtin.portals.components.voidevent.VoidEvent"
)

_VoidSpawner = _java.type(
    "com.hypixel.hytale.builtin.portals.components.voidevent.VoidSpawner"
)


class VoidEvent(Component):
    _java_class = _VoidEvent

    @property
    def active_stage(self) -> "JavaObject | None":
        return self._java.getActiveStage()

    @active_stage.setter
    def active_stage(self, value: "JavaObject") -> None:
        self._java.setActiveStage(value)

    @property
    def void_spawners(self) -> "JavaObject":
        return self._java.getVoidSpawners()


class VoidSpawner(Component):
    _java_class = _VoidSpawner

    @property
    def spawn_beacon_uuids(self) -> "JavaObject":
        return self._java.getSpawnBeaconUuids()
