# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_BlockModule_BlockStateInfo = _java.type(
    "com.hypixel.hytale.server.core.modules.block.BlockModule$BlockStateInfo"
)


class BlockModule_BlockStateInfo(Component):
    _java_class = _BlockModule_BlockStateInfo

    @property
    def chunk_ref(self) -> "JavaObject":
        return self._java.getChunkRef()

    @property
    def index(self) -> int:
        return self._java.getIndex()
