# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_ItemContainerBlock = _java.type(
    "com.hypixel.hytale.server.core.modules.block.components.ItemContainerBlock"
)


class ItemContainerBlock(Component):
    _java_class = _ItemContainerBlock

    @property
    def capacity(self) -> int:
        return self._java.getCapacity()

    @property
    def droplist(self) -> str | None:
        return self._java.getDroplist()

    @droplist.setter
    def droplist(self, value: str) -> None:
        self._java.setDroplist(value)

    @property
    def item_container(self) -> "JavaObject":
        return self._java.getItemContainer()

    @item_container.setter
    def item_container(self, value: "JavaObject") -> None:
        self._java.setItemContainer(value)

    @property
    def windows(self) -> "JavaObject":
        return self._java.getWindows()
