# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_ChainingInteraction_Data = _java.type(
    "com.hypixel.hytale.server.core.modules.interaction.interaction.config.client.ChainingInteraction$Data"
)


class ChainingInteraction_Data(Component):
    _java_class = _ChainingInteraction_Data

    @property
    def named_map(self) -> "JavaObject":
        return self._java.getNamedMap()

    @property
    def time_since_last_attack_in_seconds(self) -> float:
        return self._java.getTimeSinceLastAttackInSeconds()
