# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_AmbientEmitterComponent = _java.type(
    "com.hypixel.hytale.builtin.ambience.components.AmbientEmitterComponent"
)


class AmbientEmitterComponent(Component):
    _java_class = _AmbientEmitterComponent

    @property
    def sound_event_id(self) -> str:
        return self._java.getSoundEventId()

    @sound_event_id.setter
    def sound_event_id(self, value: str) -> None:
        self._java.setSoundEventId(value)

    @property
    def spawned_emitter(self) -> "JavaObject":
        return self._java.getSpawnedEmitter()

    @spawned_emitter.setter
    def spawned_emitter(self, value: "JavaObject") -> None:
        self._java.setSpawnedEmitter(value)
