# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

import java as _java
from pytale.components import Component

_CombatActionEvaluatorSystems_CombatConstructionData = _java.type(
    "com.hypixel.hytale.builtin.npccombatactionevaluator.CombatActionEvaluatorSystems$CombatConstructionData"
)


class CombatActionEvaluatorSystems_CombatConstructionData(Component):
    _java_class = _CombatActionEvaluatorSystems_CombatConstructionData

    @property
    def combat_state(self) -> str:
        return self._java.getCombatState()

    @combat_state.setter
    def combat_state(self, value: str) -> None:
        self._java.setCombatState(value)

    @property
    def marked_target_slot(self) -> int:
        return self._java.getMarkedTargetSlot()

    @marked_target_slot.setter
    def marked_target_slot(self, value: int) -> None:
        self._java.setMarkedTargetSlot(value)

    @property
    def max_range_slot(self) -> int:
        return self._java.getMaxRangeSlot()

    @max_range_slot.setter
    def max_range_slot(self, value: int) -> None:
        self._java.setMaxRangeSlot(value)

    @property
    def min_range_slot(self) -> int:
        return self._java.getMinRangeSlot()

    @min_range_slot.setter
    def min_range_slot(self, value: int) -> None:
        self._java.setMinRangeSlot(value)

    @property
    def positioning_angle_slot(self) -> int:
        return self._java.getPositioningAngleSlot()

    @positioning_angle_slot.setter
    def positioning_angle_slot(self, value: int) -> None:
        self._java.setPositioningAngleSlot(value)
