# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_CombatActionEvaluator = _java.type(
    "com.hypixel.hytale.builtin.npccombatactionevaluator.evaluator.CombatActionEvaluator"
)


class CombatActionEvaluator(Component):
    _java_class = _CombatActionEvaluator

    @property
    def basic_attack_target(self) -> "JavaObject | None":
        return self._java.getBasicAttackTarget()

    @basic_attack_target.setter
    def basic_attack_target(self, value: "JavaObject") -> None:
        self._java.setBasicAttackTarget(value)

    @property
    def charge_distance(self) -> float:
        return self._java.getChargeDistance()

    @property
    def charge_for(self) -> float:
        return self._java.getChargeFor()

    @property
    def current_action(self) -> "JavaObject | None":
        return self._java.getCurrentAction()

    @property
    def current_attack(self) -> str | None:
        return self._java.getCurrentAttack()

    @property
    def current_basic_attack(self) -> str | None:
        return self._java.getCurrentBasicAttack()

    @property
    def current_basic_attack_set(self) -> "JavaObject":
        return self._java.getCurrentBasicAttackSet()

    @property
    def current_interaction_type(self) -> "JavaObject":
        return self._java.getCurrentInteractionType()

    @property
    def current_interaction_vars_getter(self) -> "JavaObject":
        return self._java.getCurrentInteractionVarsGetter()

    @property
    def evaluation_context(self) -> "JavaObject":
        return self._java.getEvaluationContext()

    @property
    def last_run_nanos(self) -> int:
        return self._java.getLastRunNanos()

    @last_run_nanos.setter
    def last_run_nanos(self, value: int) -> None:
        self._java.setLastRunNanos(value)

    @property
    def marked_target_slot(self) -> int:
        return self._java.getMarkedTargetSlot()

    @property
    def max_range_slot(self) -> int:
        return self._java.getMaxRangeSlot()

    @property
    def min_range_slot(self) -> int:
        return self._java.getMinRangeSlot()

    @property
    def min_run_utility(self) -> float:
        return self._java.getMinRunUtility()

    @property
    def next_basic_attack_index(self) -> int:
        return self._java.getNextBasicAttackIndex()

    @next_basic_attack_index.setter
    def next_basic_attack_index(self, value: int) -> None:
        self._java.setNextBasicAttackIndex(value)

    @property
    def options_by_sub_state(self) -> "JavaObject":
        return self._java.getOptionsBySubState()

    @property
    def positioning_angle_slot(self) -> int:
        return self._java.getPositioningAngleSlot()

    @property
    def primary_target(self) -> "JavaObject | None":
        return self._java.getPrimaryTarget()

    @property
    def run_in_state(self) -> int:
        return self._java.getRunInState()

    @property
    def run_option(self) -> "JavaObject":
        return self._java.getRunOption()

    @property
    def should_damage_friendlies(self) -> bool:
        return self._java.shouldDamageFriendlies()

    @property
    def should_position_first(self) -> bool:
        return self._java.shouldPositionFirst()
