# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_DamageMemory = _java.type(
    "com.hypixel.hytale.builtin.npccombatactionevaluator.memory.DamageMemory"
)

_TargetMemory = _java.type(
    "com.hypixel.hytale.builtin.npccombatactionevaluator.memory.TargetMemory"
)


class DamageMemory(Component):
    _java_class = _DamageMemory

    @property
    def recent_damage(self) -> float:
        return self._java.getRecentDamage()

    @property
    def total_combat_damage(self) -> float:
        return self._java.getTotalCombatDamage()


class TargetMemory(Component):
    _java_class = _TargetMemory

    @property
    def closest_hostile(self) -> "JavaObject | None":
        return self._java.getClosestHostile()

    @closest_hostile.setter
    def closest_hostile(self, value: "JavaObject") -> None:
        self._java.setClosestHostile(value)

    @property
    def known_friendlies(self) -> "JavaObject":
        return self._java.getKnownFriendlies()

    @property
    def known_friendlies_list(self) -> "JavaObject":
        return self._java.getKnownFriendliesList()

    @property
    def known_hostiles(self) -> "JavaObject":
        return self._java.getKnownHostiles()

    @property
    def known_hostiles_list(self) -> "JavaObject":
        return self._java.getKnownHostilesList()

    @property
    def remember_for(self) -> float:
        return self._java.getRememberFor()
