# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_FallingBlock = _java.type("com.hypixel.hytale.builtin.fallingblocks.FallingBlock")


class FallingBlock(Component):
    _java_class = _FallingBlock

    @property
    def falling_block_settings(self) -> "JavaObject":
        return self._java.getFallingBlockSettings()
