# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

import java as _java
from pytale.components import Component

_ParkourCheckpoint = _java.type("com.hypixel.hytale.builtin.parkour.ParkourCheckpoint")


class ParkourCheckpoint(Component):
    _java_class = _ParkourCheckpoint

    @property
    def index(self) -> int:
        return self._java.getIndex()
