# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

import java as _java
from pytale.components import Component

_BlockPhysics = _java.type(
    "com.hypixel.hytale.server.core.blocktype.component.BlockPhysics"
)


class BlockPhysics(Component):
    _java_class = _BlockPhysics
