# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

import java as _java
from pytale.components import Component

_WeatherTracker = _java.type(
    "com.hypixel.hytale.builtin.weather.components.WeatherTracker"
)


class WeatherTracker(Component):
    _java_class = _WeatherTracker

    @property
    def environment_id(self) -> int:
        return self._java.getEnvironmentId()

    @property
    def weather_index(self) -> int:
        return self._java.getWeatherIndex()
