# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_StateEvaluator = _java.type(
    "com.hypixel.hytale.server.npc.decisionmaker.stateevaluator.StateEvaluator"
)


class StateEvaluator(Component):
    _java_class = _StateEvaluator

    @property
    def evaluation_context(self) -> "JavaObject":
        return self._java.getEvaluationContext()

    @property
    def is_active(self) -> bool:
        return self._java.isActive()

    @is_active.setter
    def is_active(self, value: bool) -> None:
        self._java.setActive(value)
