# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_PlayerSomnolence = _java.type(
    "com.hypixel.hytale.builtin.beds.sleep.components.PlayerSomnolence"
)

_SleepTracker = _java.type(
    "com.hypixel.hytale.builtin.beds.sleep.components.SleepTracker"
)


class PlayerSomnolence(Component):
    _java_class = _PlayerSomnolence

    @property
    def sleep_state(self) -> "JavaObject":
        return self._java.getSleepState()


class SleepTracker(Component):
    _java_class = _SleepTracker
