# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

import java as _java
from pytale.components import Component

_ReputationGroupComponent = _java.type(
    "com.hypixel.hytale.builtin.adventure.reputation.ReputationGroupComponent"
)


class ReputationGroupComponent(Component):
    _java_class = _ReputationGroupComponent

    @property
    def reputation_group_id(self) -> str:
        return self._java.getReputationGroupId()
