# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_FailedSpawnComponent = _java.type(
    "com.hypixel.hytale.server.npc.components.FailedSpawnComponent"
)

_SpawnBeaconReference = _java.type(
    "com.hypixel.hytale.server.npc.components.SpawnBeaconReference"
)

_SpawnMarkerReference = _java.type(
    "com.hypixel.hytale.server.npc.components.SpawnMarkerReference"
)

_SpawnReference = _java.type("com.hypixel.hytale.server.npc.components.SpawnReference")

_StepComponent = _java.type("com.hypixel.hytale.server.npc.components.StepComponent")

_Timers = _java.type("com.hypixel.hytale.server.npc.components.Timers")


class SpawnReference(Component):
    _java_class = _SpawnReference

    @property
    def reference(self) -> "JavaObject":
        return self._java.getReference()


class FailedSpawnComponent(Component):
    _java_class = _FailedSpawnComponent


class SpawnBeaconReference(SpawnReference):
    _java_class = _SpawnBeaconReference


class SpawnMarkerReference(SpawnReference):
    _java_class = _SpawnMarkerReference


class StepComponent(Component):
    _java_class = _StepComponent

    @property
    def tick_length(self) -> float:
        return self._java.getTickLength()


class Timers(Component):
    _java_class = _Timers

    @property
    def timers(self) -> "JavaObject":
        return self._java.getTimers()
