# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_BeaconSupport = _java.type(
    "com.hypixel.hytale.server.npc.components.messaging.BeaconSupport"
)

_EntityEventSupport = _java.type(
    "com.hypixel.hytale.server.npc.components.messaging.EntityEventSupport"
)

_EventSupport = _java.type(
    "com.hypixel.hytale.server.npc.components.messaging.EventSupport"
)

_MessageSupport = _java.type(
    "com.hypixel.hytale.server.npc.components.messaging.MessageSupport"
)

_NPCBlockEventSupport = _java.type(
    "com.hypixel.hytale.server.npc.components.messaging.NPCBlockEventSupport"
)

_NPCEntityEventSupport = _java.type(
    "com.hypixel.hytale.server.npc.components.messaging.NPCEntityEventSupport"
)

_PlayerBlockEventSupport = _java.type(
    "com.hypixel.hytale.server.npc.components.messaging.PlayerBlockEventSupport"
)

_PlayerEntityEventSupport = _java.type(
    "com.hypixel.hytale.server.npc.components.messaging.PlayerEntityEventSupport"
)


class EntityEventSupport(EventSupport):
    _java_class = _EntityEventSupport


class EventSupport(MessageSupport):
    _java_class = _EventSupport

    @property
    def message_slots(self) -> "JavaObject":
        return self._java.getMessageSlots()


class MessageSupport(Component):
    _java_class = _MessageSupport

    @property
    def message_slots(self) -> "JavaObject":
        return self._java.getMessageSlots()


class BeaconSupport(MessageSupport):
    _java_class = _BeaconSupport

    @property
    def message_slots(self) -> "JavaObject":
        return self._java.getMessageSlots()


class NPCBlockEventSupport(EventSupport):
    _java_class = _NPCBlockEventSupport


class NPCEntityEventSupport(EntityEventSupport):
    _java_class = _NPCEntityEventSupport


class PlayerBlockEventSupport(EventSupport):
    _java_class = _PlayerBlockEventSupport


class PlayerEntityEventSupport(EntityEventSupport):
    _java_class = _PlayerEntityEventSupport
