# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component
from pytale.math import Rotation3

if TYPE_CHECKING:
    from java import JavaObject

_PlayerRef = _java.type("com.hypixel.hytale.server.core.universe.PlayerRef")


class PlayerRef(Component):
    _java_class = _PlayerRef

    @property
    def chunk_tracker(self) -> "JavaObject":
        return self._java.getChunkTracker()

    @property
    def head_rotation(self) -> Rotation3:
        return Rotation3(self._java.getHeadRotation())

    @property
    def hidden_players_manager(self) -> "JavaObject":
        return self._java.getHiddenPlayersManager()

    @property
    def holder(self) -> "JavaObject | None":
        return self._java.getHolder()

    @property
    def is_valid(self) -> bool:
        return self._java.isValid()

    @property
    def language(self) -> str:
        return self._java.getLanguage()

    @language.setter
    def language(self, value: str) -> None:
        self._java.setLanguage(value)

    @property
    def packet_handler(self) -> "JavaObject":
        return self._java.getPacketHandler()

    @property
    def reference(self) -> "JavaObject | None":
        return self._java.getReference()

    @property
    def transform(self) -> "JavaObject":
        return self._java.getTransform()

    @property
    def username(self) -> str:
        return self._java.getUsername()

    @property
    def uuid(self) -> "JavaObject":
        return self._java.getUuid()

    @property
    def world_uuid(self) -> "JavaObject | None":
        return self._java.getWorldUuid()
