# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

import java as _java
from pytale.components import Component

_NonSerialized = _java.type("com.hypixel.hytale.component.NonSerialized")

_NonTicking = _java.type("com.hypixel.hytale.component.NonTicking")


class NonSerialized(Component):
    _java_class = _NonSerialized


class NonTicking(Component):
    _java_class = _NonTicking
