# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_WorldPathBuilder = _java.type("com.hypixel.hytale.builtin.path.WorldPathBuilder")


class WorldPathBuilder(Component):
    _java_class = _WorldPathBuilder

    @property
    def path(self) -> "JavaObject":
        return self._java.getPath()

    @path.setter
    def path(self, value: "JavaObject") -> None:
        self._java.setPath(value)
