# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_CameraManager = _java.type(
    "com.hypixel.hytale.server.core.entity.entities.player.CameraManager"
)


class CameraManager(Component):
    _java_class = _CameraManager

    @property
    def last_screen_point(self) -> "JavaObject":
        return self._java.getLastScreenPoint()

    @last_screen_point.setter
    def last_screen_point(self, value: "JavaObject") -> None:
        self._java.setLastScreenPoint(value)

    @property
    def last_target_block(self) -> "JavaObject":
        return self._java.getLastTargetBlock()
