# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

import java as _java
from pytale.components import Component

_UniqueItemUsagesComponent = _java.type(
    "com.hypixel.hytale.server.core.entity.entities.player.data.UniqueItemUsagesComponent"
)


class UniqueItemUsagesComponent(Component):
    _java_class = _UniqueItemUsagesComponent
