# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_MovementManager = _java.type(
    "com.hypixel.hytale.server.core.entity.entities.player.movement.MovementManager"
)


class MovementManager(Component):
    _java_class = _MovementManager

    @property
    def default_settings(self) -> "JavaObject":
        return self._java.getDefaultSettings()

    @property
    def settings(self) -> "JavaObject":
        return self._java.getSettings()
