# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component
from pytale.math import Vector3

if TYPE_CHECKING:
    from java import JavaObject

_UsedTeleporter = _java.type(
    "com.hypixel.hytale.builtin.adventure.teleporter.interaction.server.UsedTeleporter"
)


class UsedTeleporter(Component):
    _java_class = _UsedTeleporter

    @property
    def clear_out_xz(self) -> float:
        return self._java.getClearOutXZ()

    @property
    def clear_out_xz_squared(self) -> float:
        return self._java.getClearOutXZSquared()

    @property
    def clear_out_y(self) -> float:
        return self._java.getClearOutY()

    @property
    def destination_position(self) -> Vector3:
        return Vector3(self._java.getDestinationPosition())

    @property
    def destination_world_uuid(self) -> "JavaObject | None":
        return self._java.getDestinationWorldUuid()
