# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

import java as _java
from pytale.components import Component

_BuilderToolsUserData = _java.type(
    "com.hypixel.hytale.builtin.buildertools.BuilderToolsUserData"
)


class BuilderToolsUserData(Component):
    _java_class = _BuilderToolsUserData

    @property
    def is_recording_selection_history(self) -> bool:
        return self._java.isRecordingSelectionHistory()

    @property
    def last_save_pack(self) -> str | None:
        return self._java.getLastSavePack()

    @last_save_pack.setter
    def last_save_pack(self, value: str) -> None:
        self._java.setLastSavePack(value)
