# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

import java as _java
from pytale.components import Component

_PrefabAnchor = _java.type(
    "com.hypixel.hytale.builtin.buildertools.prefabeditor.PrefabAnchor"
)


class PrefabAnchor(Component):
    _java_class = _PrefabAnchor
