# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

import java as _java
from pytale.components import Component

_BlockSpawner = _java.type("com.hypixel.hytale.builtin.blockspawner.state.BlockSpawner")


class BlockSpawner(Component):
    _java_class = _BlockSpawner

    @property
    def block_spawner_id(self) -> str:
        return self._java.getBlockSpawnerId()

    @block_spawner_id.setter
    def block_spawner_id(self, value: str) -> None:
        self._java.setBlockSpawnerId(value)
