# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_AudioStateComponent = _java.type(
    "com.hypixel.hytale.builtin.audio.components.AudioStateComponent"
)

_ForcedMusicTracker = _java.type(
    "com.hypixel.hytale.builtin.audio.components.ForcedMusicTracker"
)


class AudioStateComponent(Component):
    _java_class = _AudioStateComponent

    @property
    def active_transition_overrides(self) -> "JavaObject":
        return self._java.getActiveTransitionOverrides()

    @property
    def current_value_indices(self) -> "JavaObject":
        return self._java.getCurrentValueIndices()

    @property
    def last_sent_value_versions(self) -> "JavaObject":
        return self._java.getLastSentValueVersions()

    @property
    def pooled_packet(self) -> "JavaObject":
        return self._java.getPooledPacket()

    @property
    def value_versions(self) -> "JavaObject":
        return self._java.getValueVersions()


class ForcedMusicTracker(Component):
    _java_class = _ForcedMusicTracker

    @property
    def current_container_index(self) -> int:
        return self._java.getCurrentContainerIndex()

    @current_container_index.setter
    def current_container_index(self, value: int) -> None:
        self._java.setCurrentContainerIndex(value)

    @property
    def last_sent_container_index(self) -> int:
        return self._java.getLastSentContainerIndex()

    @last_sent_container_index.setter
    def last_sent_container_index(self, value: int) -> None:
        self._java.setLastSentContainerIndex(value)

    @property
    def music_packet(self) -> "JavaObject":
        return self._java.getMusicPacket()
