# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

import java as _java
from pytale.components import Component

_NPCRunTestsCommand_NPCTestData = _java.type(
    "com.hypixel.hytale.server.npc.commands.NPCRunTestsCommand$NPCTestData"
)


class NPCRunTestsCommand_NPCTestData(Component):
    _java_class = _NPCRunTestsCommand_NPCTestData
