# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component
from pytale.math import Vector3

if TYPE_CHECKING:
    from java import JavaObject

_NPCEntity = _java.type("com.hypixel.hytale.server.npc.entities.NPCEntity")


class NPCEntity(Component):
    _java_class = _NPCEntity

    @property
    def active_motion_controller_name(self) -> str | None:
        return self._java.getActiveMotionControllerName()

    @active_motion_controller_name.setter
    def active_motion_controller_name(self, value: str) -> None:
        self._java.setActiveMotionControllerName(value)

    @property
    def alarm_store(self) -> "JavaObject":
        return self._java.getAlarmStore()

    @alarm_store.setter
    def alarm_store(self, value: "JavaObject") -> None:
        self._java.setAlarmStore(value)

    @property
    def blackboard_block_change_sets(self) -> "JavaObject":
        return self._java.getBlackboardBlockChangeSets()

    @property
    def blackboard_block_type_sets(self) -> "JavaObject":
        return self._java.getBlackboardBlockTypeSets()

    @property
    def blackboard_entity_event_sets(self) -> "JavaObject":
        return self._java.getBlackboardEntityEventSets()

    @property
    def damage_data(self) -> "JavaObject":
        return self._java.getDamageData()

    @property
    def despawn_time(self) -> float:
        return self._java.getDespawnTime()

    @despawn_time.setter
    def despawn_time(self, value: float) -> None:
        self._java.setDespawnTime(value)

    @property
    def environment(self) -> int:
        return self._java.getEnvironment()

    @environment.setter
    def environment(self, value: int) -> None:
        self._java.setEnvironment(value)

    @property
    def hover_height(self) -> float:
        return self._java.getHoverHeight()

    @hover_height.setter
    def hover_height(self, value: float) -> None:
        self._java.setHoverHeight(value)

    @property
    def hover_phase(self) -> float:
        return self._java.getHoverPhase()

    @hover_phase.setter
    def hover_phase(self, value: float) -> None:
        self._java.setHoverPhase(value)

    @property
    def is_despawning(self) -> bool:
        return self._java.isDespawning()

    @is_despawning.setter
    def is_despawning(self, value: bool) -> None:
        self._java.setDespawning(value)

    @property
    def is_playing_despawn_anim(self) -> bool:
        return self._java.isPlayingDespawnAnim()

    @is_playing_despawn_anim.setter
    def is_playing_despawn_anim(self, value: bool) -> None:
        self._java.setPlayingDespawnAnim(value)

    @property
    def is_reserved(self) -> bool:
        return self._java.isReserved()

    @property
    def leash_heading(self) -> float:
        return self._java.getLeashHeading()

    @leash_heading.setter
    def leash_heading(self, value: float) -> None:
        self._java.setLeashHeading(value)

    @property
    def leash_pitch(self) -> float:
        return self._java.getLeashPitch()

    @leash_pitch.setter
    def leash_pitch(self, value: float) -> None:
        self._java.setLeashPitch(value)

    @property
    def leash_point(self) -> Vector3:
        return Vector3(self._java.getLeashPoint())

    @leash_point.setter
    def leash_point(self, value: Vector3) -> None:
        self._java.setLeashPoint(value._java)

    @property
    def legacy_worldgen_id(self) -> int:
        return self._java.getLegacyWorldgenId()

    @property
    def npc_type_id(self) -> str:
        return self._java.getNPCTypeId()

    @property
    def npc_type_index(self) -> int:
        return self._java.getNPCTypeIndex()

    @property
    def old_position(self) -> Vector3:
        return Vector3(self._java.getOldPosition())

    @property
    def path_manager(self) -> "JavaObject":
        return self._java.getPathManager()

    @property
    def role(self) -> "JavaObject | None":
        return self._java.getRole()

    @role.setter
    def role(self, value: "JavaObject") -> None:
        self._java.setRole(value)

    @property
    def role_debug_flags(self) -> "JavaObject":
        return self._java.getRoleDebugFlags()

    @role_debug_flags.setter
    def role_debug_flags(self, value: "JavaObject") -> None:
        self._java.setRoleDebugFlags(value)

    @property
    def role_index(self) -> int:
        return self._java.getRoleIndex()

    @role_index.setter
    def role_index(self, value: int) -> None:
        self._java.setRoleIndex(value)

    @property
    def role_name(self) -> str:
        return self._java.getRoleName()

    @role_name.setter
    def role_name(self, value: str) -> None:
        self._java.setRoleName(value)

    @property
    def spawn_configuration(self) -> int:
        return self._java.getSpawnConfiguration()

    @spawn_configuration.setter
    def spawn_configuration(self, value: int) -> None:
        self._java.setSpawnConfiguration(value)

    @property
    def spawn_instant(self) -> "JavaObject":
        return self._java.getSpawnInstant()

    @spawn_instant.setter
    def spawn_instant(self, value: "JavaObject") -> None:
        self._java.setSpawnInstant(value)

    @property
    def spawn_role_index(self) -> int:
        return self._java.getSpawnRoleIndex()

    @spawn_role_index.setter
    def spawn_role_index(self, value: int) -> None:
        self._java.setSpawnRoleIndex(value)
