# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

import java as _java
from pytale.components import Component

_ValueStore = _java.type("com.hypixel.hytale.server.npc.valuestore.ValueStore")


class ValueStore(Component):
    _java_class = _ValueStore
