# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component
from pytale.math import Vector3

if TYPE_CHECKING:
    from java import JavaObject

_PhysicsValues = _java.type(
    "com.hypixel.hytale.server.core.modules.physics.component.PhysicsValues"
)

_Velocity = _java.type(
    "com.hypixel.hytale.server.core.modules.physics.component.Velocity"
)


class PhysicsValues(Component):
    _java_class = _PhysicsValues

    @property
    def drag_coefficient(self) -> float:
        return self._java.getDragCoefficient()

    @property
    def is_inverted_gravity(self) -> bool:
        return self._java.isInvertedGravity()

    @property
    def mass(self) -> float:
        return self._java.getMass()


class Velocity(Component):
    _java_class = _Velocity

    @property
    def client_velocity(self) -> Vector3:
        return Vector3(self._java.getClientVelocity())

    @property
    def instructions(self) -> "JavaObject":
        return self._java.getInstructions()

    @property
    def speed(self) -> float:
        return self._java.getSpeed()

    @property
    def velocity(self) -> Vector3:
        return Vector3(self._java.getVelocity())

    @property
    def x(self) -> float:
        return self._java.getX()

    @x.setter
    def x(self, value: float) -> None:
        self._java.setX(value)

    @property
    def y(self) -> float:
        return self._java.getY()

    @y.setter
    def y(self, value: float) -> None:
        self._java.setY(value)

    @property
    def z(self) -> float:
        return self._java.getZ()

    @z.setter
    def z(self, value: float) -> None:
        self._java.setZ(value)
