# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_Teleporter = _java.type(
    "com.hypixel.hytale.builtin.adventure.teleporter.component.Teleporter"
)


class Teleporter(Component):
    _java_class = _Teleporter

    @property
    def is_custom_name(self) -> bool:
        return self._java.isCustomName()

    @property
    def is_valid(self) -> bool:
        return self._java.isValid()

    @property
    def owned_warp(self) -> str | None:
        return self._java.getOwnedWarp()

    @owned_warp.setter
    def owned_warp(self, value: str) -> None:
        self._java.setOwnedWarp(value)

    @property
    def relative_mask(self) -> int:
        return self._java.getRelativeMask()

    @relative_mask.setter
    def relative_mask(self, value: int) -> None:
        self._java.setRelativeMask(value)

    @property
    def transform(self) -> "JavaObject | None":
        return self._java.getTransform()

    @transform.setter
    def transform(self, value: "JavaObject") -> None:
        self._java.setTransform(value)

    @property
    def warp(self) -> str | None:
        return self._java.getWarp()

    @warp.setter
    def warp(self, value: str) -> None:
        self._java.setWarp(value)

    @property
    def warp_name_word_list(self) -> "JavaObject | None":
        return self._java.getWarpNameWordList()

    @property
    def warp_name_word_list_key(self) -> str | None:
        return self._java.getWarpNameWordListKey()

    @warp_name_word_list_key.setter
    def warp_name_word_list_key(self, value: str) -> None:
        self._java.setWarpNameWordListKey(value)

    @property
    def world_uuid(self) -> "JavaObject | None":
        return self._java.getWorldUuid()

    @world_uuid.setter
    def world_uuid(self, value: "JavaObject") -> None:
        self._java.setWorldUuid(value)
