# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_Interactions = _java.type(
    "com.hypixel.hytale.server.core.modules.interaction.Interactions"
)


class Interactions(Component):
    _java_class = _Interactions

    @property
    def interaction_hint(self) -> str | None:
        return self._java.getInteractionHint()

    @interaction_hint.setter
    def interaction_hint(self, value: str) -> None:
        self._java.setInteractionHint(value)

    @property
    def interactions(self) -> "JavaObject":
        return self._java.getInteractions()
