# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_PlacedByInteractionComponent = _java.type(
    "com.hypixel.hytale.server.core.modules.interaction.components.PlacedByInteractionComponent"
)


class PlacedByInteractionComponent(Component):
    _java_class = _PlacedByInteractionComponent

    @property
    def who_placed_uuid(self) -> "JavaObject":
        return self._java.getWhoPlacedUuid()
