# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_SpawnMarkerBlock = _java.type(
    "com.hypixel.hytale.server.spawning.blockstates.SpawnMarkerBlock"
)

_SpawnMarkerBlockReference = _java.type(
    "com.hypixel.hytale.server.spawning.blockstates.SpawnMarkerBlockReference"
)


class SpawnMarkerBlock(Component):
    _java_class = _SpawnMarkerBlock

    @property
    def config(self) -> "JavaObject | None":
        return self._java.getConfig()

    @property
    def spawn_marker_reference(self) -> "JavaObject":
        return self._java.getSpawnMarkerReference()

    @spawn_marker_reference.setter
    def spawn_marker_reference(self, value: "JavaObject") -> None:
        self._java.setSpawnMarkerReference(value)


class SpawnMarkerBlockReference(Component):
    _java_class = _SpawnMarkerBlockReference

    @property
    def block_position(self) -> "JavaObject":
        return self._java.getBlockPosition()
