# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

import java as _java
from pytale.components import Component

_LocalSpawnBeacon = _java.type(
    "com.hypixel.hytale.server.spawning.local.LocalSpawnBeacon"
)

_LocalSpawnController = _java.type(
    "com.hypixel.hytale.server.spawning.local.LocalSpawnController"
)


class LocalSpawnBeacon(Component):
    _java_class = _LocalSpawnBeacon


class LocalSpawnController(Component):
    _java_class = _LocalSpawnController
