# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component
from pytale.math import Vector3

if TYPE_CHECKING:
    from java import JavaObject

_SpawnMarkerEntity = _java.type(
    "com.hypixel.hytale.server.spawning.spawnmarkers.SpawnMarkerEntity"
)


class SpawnMarkerEntity(Component):
    _java_class = _SpawnMarkerEntity

    @property
    def cached_marker(self) -> "JavaObject":
        return self._java.getCachedMarker()

    @cached_marker.setter
    def cached_marker(self, value: "JavaObject") -> None:
        self._java.setCachedMarker(value)

    @property
    def is_despawn_started(self) -> bool:
        return self._java.isDespawnStarted()

    @is_despawn_started.setter
    def is_despawn_started(self, value: bool) -> None:
        self._java.setDespawnStarted(value)

    @property
    def is_manual_trigger(self) -> bool:
        return self._java.isManualTrigger()

    @property
    def npc_references(self) -> "JavaObject":
        return self._java.getNpcReferences()

    @npc_references.setter
    def npc_references(self, value: "JavaObject") -> None:
        self._java.setNpcReferences(value)

    @property
    def spawn_after(self) -> "JavaObject | None":
        return self._java.getSpawnAfter()

    @spawn_after.setter
    def spawn_after(self, value: "JavaObject") -> None:
        self._java.setSpawnAfter(value)

    @property
    def spawn_count(self) -> int:
        return self._java.getSpawnCount()

    @spawn_count.setter
    def spawn_count(self, value: int) -> None:
        self._java.setSpawnCount(value)

    @property
    def spawn_marker_id(self) -> str:
        return self._java.getSpawnMarkerId()

    @property
    def spawn_position(self) -> Vector3:
        return Vector3(self._java.getSpawnPosition())

    @property
    def stored_flock(self) -> "JavaObject | None":
        return self._java.getStoredFlock()

    @stored_flock.setter
    def stored_flock(self, value: "JavaObject") -> None:
        self._java.setStoredFlock(value)

    @property
    def suppressed_by(self) -> "JavaObject | None":
        return self._java.getSuppressedBy()

    @property
    def temp_storage_list(self) -> "JavaObject | None":
        return self._java.getTempStorageList()

    @temp_storage_list.setter
    def temp_storage_list(self, value: "JavaObject") -> None:
        self._java.setTempStorageList(value)

    @property
    def time_to_deactivation(self) -> float:
        return self._java.getTimeToDeactivation()

    @time_to_deactivation.setter
    def time_to_deactivation(self, value: float) -> None:
        self._java.setTimeToDeactivation(value)
