# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

import java as _java
from pytale.components import Component

_FloodFillPositionSelector = _java.type(
    "com.hypixel.hytale.server.spawning.util.FloodFillPositionSelector"
)


class FloodFillPositionSelector(Component):
    _java_class = _FloodFillPositionSelector

    @property
    def should_rebuild_cache(self) -> bool:
        return self._java.shouldRebuildCache()
