# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component
from pytale.world import World
from typing_extensions import deprecated

if TYPE_CHECKING:
    from java import JavaObject

_BlockChunk = _java.type(
    "com.hypixel.hytale.server.core.universe.world.chunk.BlockChunk"
)

_BlockComponentChunk = _java.type(
    "com.hypixel.hytale.server.core.universe.world.chunk.BlockComponentChunk"
)

_ChunkColumn = _java.type(
    "com.hypixel.hytale.server.core.universe.world.chunk.ChunkColumn"
)

_EntityChunk = _java.type(
    "com.hypixel.hytale.server.core.universe.world.chunk.EntityChunk"
)

_WorldChunk = _java.type(
    "com.hypixel.hytale.server.core.universe.world.chunk.WorldChunk"
)


class BlockChunk(Component):
    _java_class = _BlockChunk

    @property
    def chunk_sections(self) -> "JavaObject":
        return self._java.getChunkSections()

    @property
    def environment_chunk(self) -> "JavaObject":
        return self._java.getEnvironmentChunk()

    @environment_chunk.setter
    def environment_chunk(self, value: "JavaObject") -> None:
        self._java.setEnvironmentChunk(value)

    @property
    def index(self) -> int:
        return self._java.getIndex()

    @property
    def needs_saving(self) -> bool:
        return self._java.getNeedsSaving()

    @property
    def section_count(self) -> int:
        return self._java.getSectionCount()

    @property
    def ticking_blocks_count(self) -> int:
        return self._java.getTickingBlocksCount()

    @property
    def x(self) -> int:
        return self._java.getX()

    @property
    def z(self) -> int:
        return self._java.getZ()


class BlockComponentChunk(Component):
    _java_class = _BlockComponentChunk

    @property
    def entity_holders(self) -> "JavaObject":
        return self._java.getEntityHolders()

    @property
    def entity_references(self) -> "JavaObject":
        return self._java.getEntityReferences()

    @property
    def needs_saving(self) -> bool:
        return self._java.getNeedsSaving()


@deprecated("Deprecated in Java")
class ChunkColumn(Component):
    _java_class = _ChunkColumn

    @property
    def section_holders(self) -> "JavaObject | None":
        return self._java.getSectionHolders()

    @property
    def sections(self) -> "JavaObject":
        return self._java.getSections()


class EntityChunk(Component):
    _java_class = _EntityChunk

    @property
    def entity_holders(self) -> "JavaObject":
        return self._java.getEntityHolders()

    @property
    def entity_references(self) -> "JavaObject":
        return self._java.getEntityReferences()

    @property
    def needs_saving(self) -> bool:
        return self._java.getNeedsSaving()


class WorldChunk(Component):
    _java_class = _WorldChunk

    @property
    def block_chunk(self) -> "JavaObject | None":
        return self._java.getBlockChunk()

    @property
    def block_component_chunk(self) -> "JavaObject | None":
        return self._java.getBlockComponentChunk()

    @property
    def chunk_accessor(self) -> "JavaObject":
        return self._java.getChunkAccessor()

    @property
    def entity_chunk(self) -> "JavaObject | None":
        return self._java.getEntityChunk()

    @property
    def index(self) -> int:
        return self._java.getIndex()

    @property
    def is_lighting_updates_enabled(self) -> bool:
        return self._java.isLightingUpdatesEnabled()

    @is_lighting_updates_enabled.setter
    def is_lighting_updates_enabled(self, value: bool) -> None:
        self._java.setLightingUpdatesEnabled(value)

    @property
    def is_saving(self) -> bool:
        return self._java.isSaving()

    @is_saving.setter
    def is_saving(self, value: bool) -> None:
        self._java.setSaving(value)

    @property
    def needs_saving(self) -> bool:
        return self._java.getNeedsSaving()

    @property
    def reference(self) -> "JavaObject":
        return self._java.getReference()

    @reference.setter
    def reference(self, value: "JavaObject") -> None:
        self._java.setReference(value)

    @property
    def should_keep_loaded(self) -> bool:
        return self._java.shouldKeepLoaded()

    @property
    def world(self) -> World:
        return World(self._java.getWorld())

    @property
    def x(self) -> int:
        return self._java.getX()

    @property
    def z(self) -> int:
        return self._java.getZ()
