# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

import java as _java
from pytale.components import Component

_EnvironmentChunk = _java.type(
    "com.hypixel.hytale.server.core.universe.world.chunk.environment.EnvironmentChunk"
)


class EnvironmentChunk(Component):
    _java_class = _EnvironmentChunk
