# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component
from pytale.math import Rotation3
from pytale.players import PlayerRef

if TYPE_CHECKING:
    from java import JavaObject

_BlockMountComponent = _java.type(
    "com.hypixel.hytale.builtin.mounts.BlockMountComponent"
)

_MountedByComponent = _java.type("com.hypixel.hytale.builtin.mounts.MountedByComponent")

_MountedComponent = _java.type("com.hypixel.hytale.builtin.mounts.MountedComponent")

_NPCMountComponent = _java.type("com.hypixel.hytale.builtin.mounts.NPCMountComponent")


class BlockMountComponent(Component):
    _java_class = _BlockMountComponent

    @property
    def block_pos(self) -> "JavaObject":
        return self._java.getBlockPos()

    @property
    def expected_block_type(self) -> "JavaObject":
        return self._java.getExpectedBlockType()

    @property
    def expected_rotation(self) -> int:
        return self._java.getExpectedRotation()

    @property
    def is_dead(self) -> bool:
        return self._java.isDead()

    @property
    def seated_entities(self) -> "JavaObject":
        return self._java.getSeatedEntities()

    @property
    def type(self) -> "JavaObject":
        return self._java.getType()


class MountedByComponent(Component):
    _java_class = _MountedByComponent

    @property
    def passengers(self) -> "JavaObject":
        return self._java.getPassengers()


class MountedComponent(Component):
    _java_class = _MountedComponent

    @property
    def attachment_offset(self) -> Rotation3:
        return Rotation3(self._java.getAttachmentOffset())

    @property
    def block_mount_type(self) -> "JavaObject":
        return self._java.getBlockMountType()

    @property
    def controller_type(self) -> "JavaObject":
        return self._java.getControllerType()

    @property
    def mounted_duration_ms(self) -> int:
        return self._java.getMountedDurationMs()

    @property
    def mounted_to_block(self) -> "JavaObject | None":
        return self._java.getMountedToBlock()

    @property
    def mounted_to_entity(self) -> "JavaObject | None":
        return self._java.getMountedToEntity()


class NPCMountComponent(Component):
    _java_class = _NPCMountComponent

    @property
    def anchor_x(self) -> float:
        return self._java.getAnchorX()

    @property
    def anchor_y(self) -> float:
        return self._java.getAnchorY()

    @property
    def anchor_z(self) -> float:
        return self._java.getAnchorZ()

    @property
    def original_role_index(self) -> int:
        return self._java.getOriginalRoleIndex()

    @original_role_index.setter
    def original_role_index(self, value: int) -> None:
        self._java.setOriginalRoleIndex(value)

    @property
    def owner_player_ref(self) -> PlayerRef | None:
        _value = self._java.getOwnerPlayerRef()
        return PlayerRef(_value) if _value is not None else None

    @owner_player_ref.setter
    def owner_player_ref(self, value: PlayerRef) -> None:
        self._java.setOwnerPlayerRef(value._java)
