# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_MinecartComponent = _java.type(
    "com.hypixel.hytale.builtin.mounts.minecart.MinecartComponent"
)


class MinecartComponent(Component):
    _java_class = _MinecartComponent

    @property
    def last_hit(self) -> "JavaObject | None":
        return self._java.getLastHit()

    @last_hit.setter
    def last_hit(self, value: "JavaObject") -> None:
        self._java.setLastHit(value)

    @property
    def number_of_hits(self) -> int:
        return self._java.getNumberOfHits()

    @number_of_hits.setter
    def number_of_hits(self, value: int) -> None:
        self._java.setNumberOfHits(value)

    @property
    def source_item(self) -> str:
        return self._java.getSourceItem()

    @source_item.setter
    def source_item(self, value: str) -> None:
        self._java.setSourceItem(value)
