# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_TriggerVolume = _java.type(
    "com.hypixel.hytale.builtin.triggervolumes.component.TriggerVolume"
)

_TriggerVolumeGroup = _java.type(
    "com.hypixel.hytale.builtin.triggervolumes.component.TriggerVolumeGroup"
)


class TriggerVolume(Component):
    _java_class = _TriggerVolume

    @property
    def effects(self) -> "JavaObject | None":
        return self._java.getEffects()

    @property
    def group_link_id(self) -> str | None:
        return self._java.getGroupLinkId()

    @group_link_id.setter
    def group_link_id(self, value: str) -> None:
        self._java.setGroupLinkId(value)

    @property
    def is_enabled(self) -> bool:
        return self._java.isEnabled()

    @is_enabled.setter
    def is_enabled(self, value: bool) -> None:
        self._java.setEnabled(value)

    @property
    def prefab_index(self) -> int:
        return self._java.getPrefabIndex()

    @prefab_index.setter
    def prefab_index(self, value: int) -> None:
        self._java.setPrefabIndex(value)

    @property
    def shape(self) -> "JavaObject | None":
        return self._java.getShape()


class TriggerVolumeGroup(Component):
    _java_class = _TriggerVolumeGroup

    @property
    def group_link_id(self) -> str | None:
        return self._java.getGroupLinkId()
