# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_ChunkSuppressionEntry = _java.type(
    "com.hypixel.hytale.server.spawning.suppression.component.ChunkSuppressionEntry"
)

_SpawnSuppressionComponent = _java.type(
    "com.hypixel.hytale.server.spawning.suppression.component.SpawnSuppressionComponent"
)


class ChunkSuppressionEntry(Component):
    _java_class = _ChunkSuppressionEntry

    @property
    def suppression_spans(self) -> "JavaObject":
        return self._java.getSuppressionSpans()


class SpawnSuppressionComponent(Component):
    _java_class = _SpawnSuppressionComponent

    @property
    def spawn_suppression(self) -> str:
        return self._java.getSpawnSuppression()

    @spawn_suppression.setter
    def spawn_suppression(self, value: str) -> None:
        self._java.setSpawnSuppression(value)
