# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

import java as _java
from pytale.components import Component

_CombatViewSystems_CombatData = _java.type(
    "com.hypixel.hytale.server.npc.blackboard.view.combat.CombatViewSystems$CombatData"
)


class CombatViewSystems_CombatData(Component):
    _java_class = _CombatViewSystems_CombatData
