# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_BlockSection = _java.type(
    "com.hypixel.hytale.server.core.universe.world.chunk.section.BlockSection"
)

_ChunkSection = _java.type(
    "com.hypixel.hytale.server.core.universe.world.chunk.section.ChunkSection"
)

_FluidSection = _java.type(
    "com.hypixel.hytale.server.core.universe.world.chunk.section.FluidSection"
)


class BlockSection(Component):
    _java_class = _BlockSection

    @property
    def and_clear_changed_positions(self) -> "JavaObject":
        return self._java.getAndClearChangedPositions()

    @property
    def chunk_section(self) -> "JavaObject":
        return self._java.getChunkSection()

    @chunk_section.setter
    def chunk_section(self, value: "JavaObject") -> None:
        self._java.setChunkSection(value)

    @property
    def global_change_counter(self) -> int:
        return self._java.getGlobalChangeCounter()

    @property
    def global_light(self) -> "JavaObject":
        return self._java.getGlobalLight()

    @global_light.setter
    def global_light(self, value: "JavaObject") -> None:
        self._java.setGlobalLight(value)

    @property
    def is_solid_air(self) -> bool:
        return self._java.isSolidAir()

    @property
    def local_change_counter(self) -> int:
        return self._java.getLocalChangeCounter()

    @property
    def local_light(self) -> "JavaObject":
        return self._java.getLocalLight()

    @local_light.setter
    def local_light(self, value: "JavaObject") -> None:
        self._java.setLocalLight(value)

    @property
    def maximum_hitbox_extent(self) -> float:
        return self._java.getMaximumHitboxExtent()

    @property
    def ticking_blocks_count(self) -> int:
        return self._java.getTickingBlocksCount()

    @property
    def ticking_blocks_count_copy(self) -> int:
        return self._java.getTickingBlocksCountCopy()


class ChunkSection(Component):
    _java_class = _ChunkSection

    @property
    def chunk_column_reference(self) -> "JavaObject":
        return self._java.getChunkColumnReference()

    @property
    def x(self) -> int:
        return self._java.getX()

    @property
    def y(self) -> int:
        return self._java.getY()

    @property
    def z(self) -> int:
        return self._java.getZ()


class FluidSection(Component):
    _java_class = _FluidSection

    @property
    def and_clear_changed_positions(self) -> "JavaObject":
        return self._java.getAndClearChangedPositions()

    @property
    def cached_packet(self) -> "JavaObject":
        return self._java.getCachedPacket()

    @property
    def is_empty(self) -> bool:
        return self._java.isEmpty()

    @property
    def x(self) -> int:
        return self._java.getX()

    @property
    def y(self) -> int:
        return self._java.getY()

    @property
    def z(self) -> int:
        return self._java.getZ()
