# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_BlockPositionProvider = _java.type(
    "com.hypixel.hytale.server.core.universe.world.chunk.section.blockpositions.BlockPositionProvider"
)


class BlockPositionProvider(Component):
    _java_class = _BlockPositionProvider

    @property
    def searched_block_sets(self) -> "JavaObject":
        return self._java.getSearchedBlockSets()
