# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_DespawnComponent = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.DespawnComponent"
)


class DespawnComponent(Component):
    _java_class = _DespawnComponent

    @property
    def despawn(self) -> "JavaObject | None":
        return self._java.getDespawn()

    @despawn.setter
    def despawn(self, value: "JavaObject") -> None:
        self._java.setDespawn(value)
