# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component
from pytale.math import Rotation3, Vector3
from pytale.message import Message
from typing_extensions import deprecated

if TYPE_CHECKING:
    from java import JavaObject

_ActiveAnimationComponent = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.component.ActiveAnimationComponent"
)

_AudioComponent = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.component.AudioComponent"
)

_BoundingBox = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.component.BoundingBox"
)

_BreathingComponent = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.component.BreathingComponent"
)

_CachedStatsComponent = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.component.CachedStatsComponent"
)

_CollisionResultComponent = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.component.CollisionResultComponent"
)

_DisplayNameComponent = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.component.DisplayNameComponent"
)

_DynamicLight = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.component.DynamicLight"
)

_EntityScaleComponent = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.component.EntityScaleComponent"
)

_FromPrefab = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.component.FromPrefab"
)

_FromPrefabInstance = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.component.FromPrefabInstance"
)

_FromWorldGen = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.component.FromWorldGen"
)

_HeadRotation = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.component.HeadRotation"
)

_HiddenFromAdventurePlayers = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.component.HiddenFromAdventurePlayers"
)

_Intangible = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.component.Intangible"
)

_Interactable = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.component.Interactable"
)

_Invulnerable = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.component.Invulnerable"
)

_ModelComponent = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.component.ModelComponent"
)

_MovementAudioComponent = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.component.MovementAudioComponent"
)

_NPCMarkerComponent = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.component.NPCMarkerComponent"
)

_NewSpawnComponent = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.component.NewSpawnComponent"
)

_PersistentDisplayName = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.component.PersistentDisplayName"
)

_PersistentDynamicLight = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.component.PersistentDynamicLight"
)

_PersistentModel = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.component.PersistentModel"
)

_PositionDataComponent = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.component.PositionDataComponent"
)

_PropComponent = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.component.PropComponent"
)

_RespondToHit = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.component.RespondToHit"
)

_RotateObjectComponent = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.component.RotateObjectComponent"
)

_SnapshotBuffer = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.component.SnapshotBuffer"
)

_TransformComponent = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.component.TransformComponent"
)

_WorldGenId = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.component.WorldGenId"
)


class ActiveAnimationComponent(Component):
    _java_class = _ActiveAnimationComponent

    @property
    def active_animations(self) -> "JavaObject":
        return self._java.getActiveAnimations()


class AudioComponent(Component):
    _java_class = _AudioComponent

    @property
    def sound_event_ids(self) -> "JavaObject":
        return self._java.getSoundEventIds()


class BoundingBox(Component):
    _java_class = _BoundingBox

    @property
    def bounding_box(self) -> "JavaObject":
        return self._java.getBoundingBox()

    @bounding_box.setter
    def bounding_box(self, value: "JavaObject") -> None:
        self._java.setBoundingBox(value)

    @property
    def detail_boxes(self) -> "JavaObject":
        return self._java.getDetailBoxes()

    @detail_boxes.setter
    def detail_boxes(self, value: "JavaObject") -> None:
        self._java.setDetailBoxes(value)


class BreathingComponent(Component):
    _java_class = _BreathingComponent

    @property
    def is_suffocating(self) -> bool:
        return self._java.isSuffocating()

    @is_suffocating.setter
    def is_suffocating(self, value: bool) -> None:
        self._java.setSuffocating(value)

    @property
    def last_breathing_material(self) -> "JavaObject | None":
        return self._java.getLastBreathingMaterial()

    @last_breathing_material.setter
    def last_breathing_material(self, value: "JavaObject") -> None:
        self._java.setLastBreathingMaterial(value)

    @property
    def last_fluid_id(self) -> int:
        return self._java.getLastFluidId()

    @last_fluid_id.setter
    def last_fluid_id(self, value: int) -> None:
        self._java.setLastFluidId(value)


class CachedStatsComponent(Component):
    _java_class = _CachedStatsComponent

    @property
    def is_can_breathe(self) -> bool:
        return self._java.isCanBreathe()

    @is_can_breathe.setter
    def is_can_breathe(self, value: bool) -> None:
        self._java.setCanBreathe(value)


class CollisionResultComponent(Component):
    _java_class = _CollisionResultComponent

    @property
    def collision_position_offset(self) -> Vector3:
        return Vector3(self._java.getCollisionPositionOffset())

    @property
    def collision_position_offset_copy(self) -> Vector3:
        return Vector3(self._java.getCollisionPositionOffsetCopy())

    @property
    def collision_result(self) -> "JavaObject":
        return self._java.getCollisionResult()

    @property
    def collision_start_position(self) -> Vector3:
        return Vector3(self._java.getCollisionStartPosition())

    @property
    def collision_start_position_copy(self) -> Vector3:
        return Vector3(self._java.getCollisionStartPositionCopy())

    @property
    def is_pending_collision_check(self) -> bool:
        return self._java.isPendingCollisionCheck()


class DisplayNameComponent(Component):
    _java_class = _DisplayNameComponent

    @property
    def display_name(self) -> Message | None:
        _value = self._java.getDisplayName()
        return Message(_value) if _value is not None else None


class DynamicLight(Component):
    _java_class = _DynamicLight

    @property
    def color_light(self) -> "JavaObject":
        return self._java.getColorLight()

    @color_light.setter
    def color_light(self, value: "JavaObject") -> None:
        self._java.setColorLight(value)


class EntityScaleComponent(Component):
    _java_class = _EntityScaleComponent

    @property
    def scale(self) -> float:
        return self._java.getScale()

    @scale.setter
    def scale(self, value: float) -> None:
        self._java.setScale(value)


class FromPrefab(Component):
    _java_class = _FromPrefab


class FromPrefabInstance(Component):
    _java_class = _FromPrefabInstance

    @property
    def prefab_instance_id(self) -> int:
        return self._java.getPrefabInstanceId()


class FromWorldGen(Component):
    _java_class = _FromWorldGen

    @property
    def world_gen_id(self) -> int:
        return self._java.getWorldGenId()


class HeadRotation(Component):
    _java_class = _HeadRotation

    @property
    def axis(self) -> "JavaObject":
        return self._java.getAxis()

    @property
    def axis_direction(self) -> "JavaObject":
        return self._java.getAxisDirection()

    @property
    def direction(self) -> Vector3:
        return Vector3(self._java.getDirection())

    @property
    def horizontal_axis_direction(self) -> "JavaObject":
        return self._java.getHorizontalAxisDirection()

    @property
    def rotation(self) -> Rotation3:
        return Rotation3(self._java.getRotation())

    @rotation.setter
    def rotation(self, value: Rotation3) -> None:
        self._java.setRotation(value._java)


class HiddenFromAdventurePlayers(Component):
    _java_class = _HiddenFromAdventurePlayers


class Intangible(Component):
    _java_class = _Intangible


class Interactable(Component):
    _java_class = _Interactable


class Invulnerable(Component):
    _java_class = _Invulnerable


class ModelComponent(Component):
    _java_class = _ModelComponent

    @property
    def model(self) -> "JavaObject":
        return self._java.getModel()


class MovementAudioComponent(Component):
    _java_class = _MovementAudioComponent

    @property
    def can_move_in_repeat(self) -> bool:
        return self._java.canMoveInRepeat()

    @property
    def last_inside_block_type_id(self) -> int:
        return self._java.getLastInsideBlockTypeId()

    @last_inside_block_type_id.setter
    def last_inside_block_type_id(self, value: int) -> None:
        self._java.setLastInsideBlockTypeId(value)


@deprecated("Deprecated in Java")
class NPCMarkerComponent(Component):
    _java_class = _NPCMarkerComponent


class NewSpawnComponent(Component):
    _java_class = _NewSpawnComponent


class PersistentDisplayName(Component):
    _java_class = _PersistentDisplayName

    @property
    def display_name(self) -> Message | None:
        _value = self._java.getDisplayName()
        return Message(_value) if _value is not None else None


class PersistentDynamicLight(Component):
    _java_class = _PersistentDynamicLight

    @property
    def color_light(self) -> "JavaObject":
        return self._java.getColorLight()

    @color_light.setter
    def color_light(self, value: "JavaObject") -> None:
        self._java.setColorLight(value)


class PersistentModel(Component):
    _java_class = _PersistentModel

    @property
    def model_reference(self) -> "JavaObject":
        return self._java.getModelReference()

    @model_reference.setter
    def model_reference(self, value: "JavaObject") -> None:
        self._java.setModelReference(value)


class PositionDataComponent(Component):
    _java_class = _PositionDataComponent

    @property
    def inside_block_type_id(self) -> int:
        return self._java.getInsideBlockTypeId()

    @inside_block_type_id.setter
    def inside_block_type_id(self, value: int) -> None:
        self._java.setInsideBlockTypeId(value)

    @property
    def standing_on_block_type_id(self) -> int:
        return self._java.getStandingOnBlockTypeId()

    @standing_on_block_type_id.setter
    def standing_on_block_type_id(self, value: int) -> None:
        self._java.setStandingOnBlockTypeId(value)


class PropComponent(Component):
    _java_class = _PropComponent


class RespondToHit(Component):
    _java_class = _RespondToHit


class RotateObjectComponent(Component):
    _java_class = _RotateObjectComponent

    @property
    def rotation_speed(self) -> float:
        return self._java.getRotationSpeed()

    @rotation_speed.setter
    def rotation_speed(self, value: float) -> None:
        self._java.setRotationSpeed(value)


class SnapshotBuffer(Component):
    _java_class = _SnapshotBuffer

    @property
    def current_tick_index(self) -> int:
        return self._java.getCurrentTickIndex()

    @property
    def is_initialized(self) -> bool:
        return self._java.isInitialized()

    @property
    def oldest_tick_index(self) -> int:
        return self._java.getOldestTickIndex()


class TransformComponent(Component):
    _java_class = _TransformComponent

    @property
    def chunk(self) -> "JavaObject | None":
        return self._java.getChunk()

    @property
    def chunk_ref(self) -> "JavaObject | None":
        return self._java.getChunkRef()

    @property
    def position(self) -> Vector3:
        return Vector3(self._java.getPosition())

    @position.setter
    def position(self, value: Vector3) -> None:
        self._java.setPosition(value._java)

    @property
    def rotation(self) -> Rotation3:
        return Rotation3(self._java.getRotation())

    @rotation.setter
    def rotation(self, value: Rotation3) -> None:
        self._java.setRotation(value._java)

    @property
    def sent_transform(self) -> "JavaObject":
        return self._java.getSentTransform()

    @property
    def transform(self) -> "JavaObject":
        return self._java.getTransform()


class WorldGenId(Component):
    _java_class = _WorldGenId

    @property
    def world_gen_id(self) -> int:
        return self._java.getWorldGenId()
