# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component
from pytale.message import Message

if TYPE_CHECKING:
    from java import JavaObject

_DeathComponent = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.damage.DeathComponent"
)

_DeferredCorpseRemoval = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.damage.DeferredCorpseRemoval"
)


class DeathComponent(Component):
    _java_class = _DeathComponent

    @property
    def death_cause(self) -> "JavaObject | None":
        return self._java.getDeathCause()

    @property
    def death_info(self) -> "JavaObject | None":
        return self._java.getDeathInfo()

    @property
    def death_item_loss(self) -> "JavaObject":
        return self._java.getDeathItemLoss()

    @property
    def death_message(self) -> Message | None:
        _value = self._java.getDeathMessage()
        return Message(_value) if _value is not None else None

    @death_message.setter
    def death_message(self, value: Message) -> None:
        self._java.setDeathMessage(value._java)

    @property
    def interaction_chain(self) -> "JavaObject | None":
        return self._java.getInteractionChain()

    @interaction_chain.setter
    def interaction_chain(self, value: "JavaObject") -> None:
        self._java.setInteractionChain(value)

    @property
    def is_show_death_menu(self) -> bool:
        return self._java.isShowDeathMenu()

    @is_show_death_menu.setter
    def is_show_death_menu(self, value: bool) -> None:
        self._java.setShowDeathMenu(value)

    @property
    def items_amount_loss_percentage(self) -> float:
        return self._java.getItemsAmountLossPercentage()

    @items_amount_loss_percentage.setter
    def items_amount_loss_percentage(self, value: float) -> None:
        self._java.setItemsAmountLossPercentage(value)

    @property
    def items_durability_loss_percentage(self) -> float:
        return self._java.getItemsDurabilityLossPercentage()

    @items_durability_loss_percentage.setter
    def items_durability_loss_percentage(self, value: float) -> None:
        self._java.setItemsDurabilityLossPercentage(value)

    @property
    def items_loss_mode(self) -> "JavaObject":
        return self._java.getItemsLossMode()

    @items_loss_mode.setter
    def items_loss_mode(self, value: "JavaObject") -> None:
        self._java.setItemsLossMode(value)

    @property
    def items_lost_on_death(self) -> "JavaObject":
        return self._java.getItemsLostOnDeath()

    @items_lost_on_death.setter
    def items_lost_on_death(self, value: "JavaObject") -> None:
        self._java.setItemsLostOnDeath(value)


class DeferredCorpseRemoval(Component):
    _java_class = _DeferredCorpseRemoval

    @property
    def death_particles(self) -> str | None:
        return self._java.getDeathParticles()

    @property
    def should_remove(self) -> bool:
        return self._java.shouldRemove()
