# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

import java as _java
from pytale.components import Component

_HitboxCollision = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.hitboxcollision.HitboxCollision"
)


class HitboxCollision(Component):
    _java_class = _HitboxCollision

    @property
    def hitbox_collision_config_id(self) -> str | None:
        return self._java.getHitboxCollisionConfigId()

    @property
    def hitbox_collision_config_index(self) -> int:
        return self._java.getHitboxCollisionConfigIndex()

    @property
    def is_migrated(self) -> bool:
        return self._java.isMigrated()
