# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component
from pytale.math import Vector3
from typing_extensions import deprecated

if TYPE_CHECKING:
    from java import JavaObject

_ItemComponent = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.item.ItemComponent"
)

_ItemPhysicsComponent = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.item.ItemPhysicsComponent"
)

_PickupItemComponent = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.item.PickupItemComponent"
)

_PreventItemMerging = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.item.PreventItemMerging"
)

_PreventPickup = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.item.PreventPickup"
)


class ItemComponent(Component):
    _java_class = _ItemComponent

    @property
    def can_pick_up(self) -> bool:
        return self._java.canPickUp()

    @property
    def is_removed_by_player_pickup(self) -> bool:
        return self._java.isRemovedByPlayerPickup()

    @is_removed_by_player_pickup.setter
    def is_removed_by_player_pickup(self, value: bool) -> None:
        self._java.setRemovedByPlayerPickup(value)

    @property
    def item_stack(self) -> "JavaObject | None":
        return self._java.getItemStack()

    @item_stack.setter
    def item_stack(self, value: "JavaObject") -> None:
        self._java.setItemStack(value)


@deprecated("Deprecated in Java")
class ItemPhysicsComponent(Component):
    _java_class = _ItemPhysicsComponent


class PickupItemComponent(Component):
    _java_class = _PickupItemComponent

    @property
    def life_time(self) -> float:
        return self._java.getLifeTime()

    @property
    def original_life_time(self) -> float:
        return self._java.getOriginalLifeTime()

    @property
    def start_position(self) -> Vector3:
        return Vector3(self._java.getStartPosition())

    @property
    def target_ref(self) -> "JavaObject | None":
        return self._java.getTargetRef()


class PreventItemMerging(Component):
    _java_class = _PreventItemMerging


class PreventPickup(Component):
    _java_class = _PreventPickup
