# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component
from pytale.math import Vector3
from pytale.message import Message

if TYPE_CHECKING:
    from java import JavaObject

_ApplyRandomSkinPersistedComponent = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.player.ApplyRandomSkinPersistedComponent"
)

_ChunkTracker = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.player.ChunkTracker"
)

_KnockbackSimulation = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.player.KnockbackSimulation"
)

_PlayerInput = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.player.PlayerInput"
)

_PlayerSettings = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.player.PlayerSettings"
)

_PlayerSkinComponent = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.player.PlayerSkinComponent"
)


class ApplyRandomSkinPersistedComponent(Component):
    _java_class = _ApplyRandomSkinPersistedComponent


class ChunkTracker(Component):
    _java_class = _ChunkTracker

    @property
    def is_ready_for_chunks(self) -> bool:
        return self._java.isReadyForChunks()

    @is_ready_for_chunks.setter
    def is_ready_for_chunks(self, value: bool) -> None:
        self._java.setReadyForChunks(value)

    @property
    def loaded_chunks_count(self) -> int:
        return self._java.getLoadedChunksCount()

    @property
    def loaded_chunks_debug(self) -> str:
        return self._java.getLoadedChunksDebug()

    @property
    def loaded_chunks_message(self) -> Message:
        return Message(self._java.getLoadedChunksMessage())

    @property
    def loading_chunks_count(self) -> int:
        return self._java.getLoadingChunksCount()

    @property
    def max_chunks_per_second(self) -> int:
        return self._java.getMaxChunksPerSecond()

    @max_chunks_per_second.setter
    def max_chunks_per_second(self, value: int) -> None:
        self._java.setMaxChunksPerSecond(value)

    @property
    def max_chunks_per_tick(self) -> int:
        return self._java.getMaxChunksPerTick()

    @max_chunks_per_tick.setter
    def max_chunks_per_tick(self, value: int) -> None:
        self._java.setMaxChunksPerTick(value)

    @property
    def max_hot_loaded_chunks_radius(self) -> int:
        return self._java.getMaxHotLoadedChunksRadius()

    @max_hot_loaded_chunks_radius.setter
    def max_hot_loaded_chunks_radius(self, value: int) -> None:
        self._java.setMaxHotLoadedChunksRadius(value)

    @property
    def min_loaded_chunks_radius(self) -> int:
        return self._java.getMinLoadedChunksRadius()

    @min_loaded_chunks_radius.setter
    def min_loaded_chunks_radius(self, value: int) -> None:
        self._java.setMinLoadedChunksRadius(value)


class KnockbackSimulation(Component):
    _java_class = _KnockbackSimulation

    @property
    def check_position(self) -> Vector3:
        return Vector3(self._java.getCheckPosition())

    @property
    def client_last_position(self) -> Vector3:
        return Vector3(self._java.getClientLastPosition())

    @property
    def client_movement_states(self) -> "JavaObject":
        return self._java.getClientMovementStates()

    @client_movement_states.setter
    def client_movement_states(self, value: "JavaObject") -> None:
        self._java.setClientMovementStates(value)

    @property
    def client_position(self) -> Vector3:
        return Vector3(self._java.getClientPosition())

    @property
    def collision_result(self) -> "JavaObject":
        return self._java.getCollisionResult()

    @property
    def is_client_finished(self) -> bool:
        return self._java.isClientFinished()

    @is_client_finished.setter
    def is_client_finished(self, value: bool) -> None:
        self._java.setClientFinished(value)

    @property
    def jump_combo(self) -> int:
        return self._java.getJumpCombo()

    @jump_combo.setter
    def jump_combo(self, value: int) -> None:
        self._java.setJumpCombo(value)

    @property
    def movement_offset(self) -> Vector3:
        return Vector3(self._java.getMovementOffset())

    @property
    def relative_movement(self) -> Vector3:
        return Vector3(self._java.getRelativeMovement())

    @property
    def remaining_time(self) -> float:
        return self._java.getRemainingTime()

    @remaining_time.setter
    def remaining_time(self, value: float) -> None:
        self._java.setRemainingTime(value)

    @property
    def requested_velocity(self) -> Vector3:
        return Vector3(self._java.getRequestedVelocity())

    @requested_velocity.setter
    def requested_velocity(self, value: Vector3) -> None:
        self._java.setRequestedVelocity(value._java)

    @property
    def requested_velocity_change_type(self) -> "JavaObject | None":
        return self._java.getRequestedVelocityChangeType()

    @requested_velocity_change_type.setter
    def requested_velocity_change_type(self, value: "JavaObject") -> None:
        self._java.setRequestedVelocityChangeType(value)

    @property
    def sim_position(self) -> Vector3:
        return Vector3(self._java.getSimPosition())

    @property
    def sim_velocity(self) -> Vector3:
        return Vector3(self._java.getSimVelocity())

    @property
    def temp_position(self) -> Vector3:
        return Vector3(self._java.getTempPosition())

    @property
    def tick_buffer(self) -> float:
        return self._java.getTickBuffer()

    @tick_buffer.setter
    def tick_buffer(self, value: float) -> None:
        self._java.setTickBuffer(value)


class PlayerInput(Component):
    _java_class = _PlayerInput

    @property
    def mount_id(self) -> int:
        return self._java.getMountId()

    @mount_id.setter
    def mount_id(self, value: int) -> None:
        self._java.setMountId(value)

    @property
    def movement_update_queue(self) -> "JavaObject":
        return self._java.getMovementUpdateQueue()


class PlayerSettings(Component):
    _java_class = _PlayerSettings


class PlayerSkinComponent(Component):
    _java_class = _PlayerSkinComponent

    @property
    def player_skin(self) -> "JavaObject":
        return self._java.getPlayerSkin()
