# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

import java as _java
from pytale.components import Component

_Repulsion = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.repulsion.Repulsion"
)


class Repulsion(Component):
    _java_class = _Repulsion

    @property
    def is_migrated(self) -> bool:
        return self._java.isMigrated()

    @property
    def repulsion_config_id(self) -> str | None:
        return self._java.getRepulsionConfigId()

    @property
    def repulsion_config_index(self) -> int:
        return self._java.getRepulsionConfigIndex()
