# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component
from pytale.math import Rotation3, Vector3
from pytale.world import World

if TYPE_CHECKING:
    from java import JavaObject

_PendingTeleport = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.teleport.PendingTeleport"
)

_Teleport = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.teleport.Teleport"
)

_TeleportRecord = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.teleport.TeleportRecord"
)


class PendingTeleport(Component):
    _java_class = _PendingTeleport

    @property
    def is_empty(self) -> bool:
        return self._java.isEmpty()

    @property
    def position(self) -> Vector3:
        return Vector3(self._java.getPosition())


class Teleport(Component):
    _java_class = _Teleport

    @property
    def head_rotation(self) -> Rotation3 | None:
        _value = self._java.getHeadRotation()
        return Rotation3(_value) if _value is not None else None

    @property
    def is_reset_velocity(self) -> bool:
        return self._java.isResetVelocity()

    @property
    def on_complete(self) -> "JavaObject":
        return self._java.getOnComplete()

    @on_complete.setter
    def on_complete(self, value: "JavaObject") -> None:
        self._java.setOnComplete(value)

    @property
    def position(self) -> Vector3:
        return Vector3(self._java.getPosition())

    @position.setter
    def position(self, value: Vector3) -> None:
        self._java.setPosition(value._java)

    @property
    def rotation(self) -> Rotation3:
        return Rotation3(self._java.getRotation())

    @rotation.setter
    def rotation(self, value: Rotation3) -> None:
        self._java.setRotation(value._java)

    @property
    def world(self) -> World | None:
        _value = self._java.getWorld()
        return World(_value) if _value is not None else None


class TeleportRecord(Component):
    _java_class = _TeleportRecord

    @property
    def last_teleport(self) -> "JavaObject | None":
        return self._java.getLastTeleport()

    @last_teleport.setter
    def last_teleport(self, value: "JavaObject") -> None:
        self._java.setLastTeleport(value)
