# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

import java as _java
from pytale.components import Component

_EntityTrackerSystems_EntityViewer = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.tracker.EntityTrackerSystems$EntityViewer"
)

_EntityTrackerSystems_Visible = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.tracker.EntityTrackerSystems$Visible"
)

_NetworkId = _java.type(
    "com.hypixel.hytale.server.core.modules.entity.tracker.NetworkId"
)


class EntityTrackerSystems_EntityViewer(Component):
    _java_class = _EntityTrackerSystems_EntityViewer


class EntityTrackerSystems_Visible(Component):
    _java_class = _EntityTrackerSystems_Visible


class NetworkId(Component):
    _java_class = _NetworkId

    @property
    def id(self) -> int:
        return self._java.getId()
