# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_CoopResidentComponent = _java.type(
    "com.hypixel.hytale.builtin.adventure.farming.component.CoopResidentComponent"
)


class CoopResidentComponent(Component):
    _java_class = _CoopResidentComponent

    @property
    def coop_location(self) -> "JavaObject":
        return self._java.getCoopLocation()

    @coop_location.setter
    def coop_location(self, value: "JavaObject") -> None:
        self._java.setCoopLocation(value)

    @property
    def marked_for_despawn(self) -> bool:
        return self._java.getMarkedForDespawn()

    @marked_for_despawn.setter
    def marked_for_despawn(self, value: bool) -> None:
        self._java.setMarkedForDespawn(value)
