# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_CoopBlock = _java.type("com.hypixel.hytale.builtin.adventure.farming.states.CoopBlock")

_FarmingBlock = _java.type(
    "com.hypixel.hytale.builtin.adventure.farming.states.FarmingBlock"
)

_TilledSoilBlock = _java.type(
    "com.hypixel.hytale.builtin.adventure.farming.states.TilledSoilBlock"
)


class CoopBlock(Component):
    _java_class = _CoopBlock

    @property
    def coop_asset(self) -> "JavaObject | None":
        return self._java.getCoopAsset()


class FarmingBlock(Component):
    _java_class = _FarmingBlock

    @property
    def current_stage_set(self) -> str:
        return self._java.getCurrentStageSet()

    @current_stage_set.setter
    def current_stage_set(self, value: str) -> None:
        self._java.setCurrentStageSet(value)

    @property
    def executions(self) -> int:
        return self._java.getExecutions()

    @executions.setter
    def executions(self, value: int) -> None:
        self._java.setExecutions(value)

    @property
    def generation(self) -> int:
        return self._java.getGeneration()

    @generation.setter
    def generation(self, value: int) -> None:
        self._java.setGeneration(value)

    @property
    def growth_progress(self) -> float:
        return self._java.getGrowthProgress()

    @growth_progress.setter
    def growth_progress(self, value: float) -> None:
        self._java.setGrowthProgress(value)

    @property
    def last_tick_game_time(self) -> "JavaObject":
        return self._java.getLastTickGameTime()

    @last_tick_game_time.setter
    def last_tick_game_time(self, value: "JavaObject") -> None:
        self._java.setLastTickGameTime(value)

    @property
    def previous_block_type(self) -> str:
        return self._java.getPreviousBlockType()

    @previous_block_type.setter
    def previous_block_type(self, value: str) -> None:
        self._java.setPreviousBlockType(value)

    @property
    def spread_rate(self) -> float:
        return self._java.getSpreadRate()

    @spread_rate.setter
    def spread_rate(self, value: float) -> None:
        self._java.setSpreadRate(value)


class TilledSoilBlock(Component):
    _java_class = _TilledSoilBlock

    @property
    def decay_time(self) -> "JavaObject | None":
        return self._java.getDecayTime()

    @decay_time.setter
    def decay_time(self, value: "JavaObject") -> None:
        self._java.setDecayTime(value)

    @property
    def is_fertilized(self) -> bool:
        return self._java.isFertilized()

    @is_fertilized.setter
    def is_fertilized(self, value: bool) -> None:
        self._java.setFertilized(value)

    @property
    def is_planted(self) -> bool:
        return self._java.isPlanted()

    @is_planted.setter
    def is_planted(self, value: bool) -> None:
        self._java.setPlanted(value)

    @property
    def watered_until(self) -> "JavaObject | None":
        return self._java.getWateredUntil()

    @watered_until.setter
    def watered_until(self, value: "JavaObject") -> None:
        self._java.setWateredUntil(value)
